spring.application.name=MyPass
spring.jpa.defer-datasource-initialization=true

#spring.security.user.name=admin
#spring.security.user.password=admin

# RSA KEYS
rsa.private-key=classpath:keys/private_key.pem
rsa.public-key=classpath:keys/public_key.pem
